version: "3.8"

services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    environment:
      TZ: ${TIMEZONE}
    volumes:
      - ../hosts:/etc/nginx/conf.d
      - ../www:/var/www
      - ../data/certs/hosts:/var/certs
      - ../logs/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
      - "8084:8084"
      - "8085:8085"
      - "8086:8086"
    networks:
      - workspace