version: "3.8"

services:
  apache:
    image: httpd:latest
    restart: unless-stopped
    environment:
      TZ: ${TIMEZONE}
    volumes:
      - ../images/apache/my-httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ../hosts/apache:/etc/apache2/sites-available
      - ../data/certs/hosts:/var/certs
      - ../logs/apache:/var/log/apache
    ports:
      - "80:80"
      - "443:443"
      - "8084:8084"
      - "8085:8085"
      - "8086:8086"
    networks:
      - workspace