version: "3.8"

services:
  php:
    build:
      context: ../images/php
      dockerfile: ${PHP_VER}.Dockerfile
      args:
        - USER_ID
        - GROUP_ID
    restart: unless-stopped
    environment:
      PHP_IDE_CONFIG: serverName=${XDEBUG_SERVERNAME}
      TZ: ${TIMEZONE}
    working_dir: /var/www
    volumes:
      - ../images/php/php${PHP_VER}.ini:/usr/local/etc/php/conf.d/40-custom.ini
      - ../data/certs/ca:/usr/local/etc/ca
      - ../images/php/msmtprc:/etc/msmtprc
      - ../data/mails:/var/mail/sendmail
      - ../data/certs/mnt:/home/docker/certs
      - ../data/cache/.composer:/home/docker/.composer
      - ../data/cache/.npm:/home/docker/.npm
      - ../logs/php:/var/log/php
      - ../logs/msmtp:/var/log/msmtp
    networks:
      - workspace