version: "3.8"

services:
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      TZ: ${TIMEZONE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    entrypoint: ""
    command: ["sh", "-c", "chown -R mysql:mysql /var/log/mysql && exec /entrypoint.sh mysqld --default-authentication-plugin=mysql_native_password"]
    volumes:
      - ../data/databases/mysql:/var/lib/mysql
      - ../images/mysql/my.cnf:/etc/mysql/conf.d/40-config-file.cnf
      - ../logs/mysql:/var/log/mysql
    ports:
      - "3306:3306"
    networks:
      - workspace