version: "3.8"

services:
  mongo-express:
    image: mongo-express
    depends_on:
      - "mongo"
    restart: unless-stopped
    ports:
      - "8083:8081"
    environment:
      TZ: ${TIMEZONE}
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${BASICAUTH_PASSWORD}
    networks:
      - workspace
