version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:management
    restart: unless-stopped
    hostname: ws-rabbit
    environment:
      TZ: ${TIMEZONE}
#      RABBITMQ_DEFAULT_USER: ${DB_USER}
#      RABBITMQ_DEFAULT_PASS: ${DB_PASSWORD}
    volumes:
      - ../data/databases/rabbitmq:/var/lib/rabbitmq/mnesia
      - ../images/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - "5672:5672"
      - "8088:15672"
    networks:
      - workspace